### ISSUE TITLE
Circular border

### ISSUE THREAD

**Issue by fabioselau077** [rickywen911/custom_bubble_navigation_bar#1]
Is it possible to add a circular border on the top left and top right?
Example: 
![Example](https://cdn.dribbble.com/users/4189231/screenshots/8084058/media/3c1ca98c6bc962611db7679f4fc4b4d0.jpg)

**Comment by rickywen911** [comment]
Thanks for the issue, I'll take a look and make an update when it's done

**Comment by rickywen911** [comment]
@fabioselau077 Hi, I have add border radius in version 0.2.5, please check the example app for more information, Thanks for the suggestion!
