### ISSUE TITLE
elevation not working

### ISSUE THREAD

**Issue by dmrcierhn** [rickywen911/custom_bubble_navigation_bar#11]
I want to use elevation but it doesn't work for me. I tried on emulator and real device but no results. how can i use ? Thank you

**Comment by rickywen911** [comment]
@dmrcierhn Thanks for using my package. 
I tried change the elevation value in the constructor of NavBar but it seems that the elevation was very unclear when I set the value larger than 30. It seems that `elevation` in the constructor can only control if elevation to show or not.
This is app bar without elevation
<img width="415" alt="noelevation" src="https://user-images.githubusercontent.com/14174810/103143049-a595c880-46d4-11eb-805f-f3f4d8d1163d.png">
This is app bar with elevation
<img width="415" alt="8elevation" src="https://user-images.githubusercontent.com/14174810/103143057-d8d85780-46d4-11eb-9dda-3f3574e746fe.png">
I searched the stackoverflow and got this answer <https://stackoverflow.com/questions/53299232/elevation-not-working-on-flutter-material>
So if you want a stronger elevation, You can try to use [BoxDecoration](https://api.flutter.dev/flutter/painting/BoxDecoration-class.html) to rewrite this package.
Thanks again.
