### ISSUE TITLE
When a CustomNavigationBarItem takes up more space, items go off center

### ISSUE THREAD

**Issue by SilkeNL** [rickywen911/custom_bubble_navigation_bar#17]
So I have 3 NavbarItems all with a title of text. In the first one the text is longer, pushing the other 2 off center and to the side.

So instead of
---1---2---3---
its
---1----2---3--

Which seems odd since there is more than enough space for all 3 text widgets

**Comment by SilkeNL** [comment]
@rickywen911

**Comment by rickywen911** [comment]
@SilkeNL Thanks for pointing out. I'll check it later.

**Comment by uttusharma** [comment]
https://github.com/rickywen911/custom_bubble_navigation_bar/pull/20

Hey, 
I have fixed this issue in this PR

**Comment by uttusharma** [comment]
Hey I have fixed this issue in PR https://github.com/rickywen911/custom_bubble_navigation_bar/pull/20

Use it like this 
```
 CustomNavigationBarItem(
          icon: Icon(Icons.home),
          title: Text(
            "Homeeeeeeeee",
            overflow: TextOverflow.ellipsis,
          ),
        ),
```
