### ISSUE TITLE
Requesting Flutter Null Safety Support

### ISSUE THREAD

**Issue by princeteck** [rickywen911/custom_bubble_navigation_bar#18]
Facing Null Safety support issue for `v2.12.0`. Please update the code as per requirement.

```Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

- package:custom_navigation_bar
```

**Comment by rickywen911** [comment]
@princeteck Thanks for the issue. I will update it in next two weeks.

**Comment by rickywen911** [comment]
updated at version 0.8.0, closed for now.
