### ISSUE TITLE
The animation doesn't end with a quick switch.

### ISSUE THREAD

**Issue by XUXAYM** [rickywen911/custom_bubble_navigation_bar#21]
Hello, i found one issue, which doesn't let me implement this widget to my app. 
When i switching between tabs quickly, animation of icon growing isn't fully animated and icon remains large
### Here is normal size of icon.
![image](https://user-images.githubusercontent.com/42353842/119955560-d4c4a480-bfa8-11eb-94c7-bc238dfd5dc5.png)
### Here is zoomed cart icon. 
![image](https://user-images.githubusercontent.com/42353842/119955506-c5ddf200-bfa8-11eb-9e97-a18f90b8fd9d.png)

**Comment by XUXAYM** [comment]
@rickywen911

**Comment by rickywen911** [comment]
@XUXAYM Thanks for pointing out. I will check it later. BTW, would you mind show me the `flutter doctor` you have right now?

**Comment by lcm1475** [comment]
I have the same problem. If I click on different items quickly, it will definitely happen

**Comment by lcm1475** [comment]
快速点击这些item 就会出现 因为上次的动画还没执行完毕

**Comment by rickywen911** [comment]
@lcm1475 Thanks for pointing out. I will fix it later.

**Comment by rickywen911** [comment]
Fix in version 0.8.2, close for now.
