### ISSUE TITLE
support iOS dark mode ?

### ISSUE THREAD

**Issue by einsitang** [rickywen911/custom_bubble_navigation_bar#32]
this component so good to me , but demo on iOS with dark mode look like not so well.

![Dark Mode](https://github.com/rickywen911/custom_bubble_navigation_bar/assets/1745525/1820d279-18b0-48f9-9e97-b9ffa810dcd0)

![Light Mode](https://github.com/rickywen911/custom_bubble_navigation_bar/assets/1745525/9091b239-26ad-472a-b02e-1b00e1b8cf2c)

**Comment by rickywen911** [comment]
Hi @einsitang thanks for using this library. Unfortunly I don't have enough time to maintain this repo anymore due to work issue, so you can try to add support for dark mode by yourself if you want.

**Comment by einsitang** [comment]
> Hi @einsitang thanks for using this library. Unfortunly I don't have enough time to maintain this repo anymore due to work issue, so you can try to add support for dark mode by yourself if you want.

thanks for reply . 
I think I can contribution this feature . for my project seem work finel and PR later

**Comment by einsitang** [comment]
PR #33
