### ISSUE TITLE
Increasing the gesture area per CustomNavigationBarItem

### ISSUE THREAD

**Issue by adeolaex** [rickywen911/custom_bubble_navigation_bar#5]
Thank you for this great package.

**Feature Request**

Would it be possible to increase the gesture area for each CustomNavigationBarItem ? For example the CupertinoTabScaffold 's TabBar takes on the default behaviour of not only tapping on the Icon itself, but rather tapping on the Icon and its relative surrounding. 

This makes it easier for users to easily change tabs without aiming directly for the Icons or better still, expose the animations to a CupertinoTabScaffold.

**Comment by rickywen911** [comment]
Thanks for the request! I will look into it and update in next version.

**Comment by adeolaex** [comment]
Thank you very much !

**Comment by rickywen911** [comment]
@adeolaex Hi there, I have updated the feature in the version 0.4.0. Thanks again for this request!

**Comment by rickywen911** [comment]
Updated in version 0.4.0, closed for now

**Comment by adeolaex** [comment]
@rickywen911 Just upgrade to v 0.4.0 and tested it out.

 Thank you very much for that adding that feature.
