### ISSUE TITLE
Use Svg rather than IconData

### ISSUE THREAD

**Issue by llastkrakw** [rickywen911/custom_bubble_navigation_bar#8]
Hi , great job but i want to use svg with SvgPicture rather than IconData. I don't know if is possible to use both of them.
Thanks

**Comment by rickywen911** [comment]
@llastkrakw Hi, I think it's possible. I will add this feature to the project road map. Thanks for issue again!

**Comment by llastkrakw** [comment]
great, thanks.

**Comment by rickywen911** [comment]
Will update in version 0.6.0

**Comment by rickywen911** [comment]
@llastkrakw I have update version 0.6.0. Now the `icon` is a `Widget` rather than `IconData`. You can try to put a svg image in it. Enjoy!

**Comment by llastkrakw** [comment]
Cool, nice and thanks
